### ISSUE TITLE
center align function 

### ISSUE THREAD

**Issue by nerd-deus** [MFReaper/HeaderFile-Lexicon#9]
I was using this function and when using it:- 
`center_align( int )` somehow it didn't work.
`center_align( char* )` took the `put` pointer to the top of the console and then center aligned the string.

**Comment by MFReaper** [comment]
Please check the following link:
https://github.com/MFReaper/HeaderFile-Lexicon/wiki/Functions-(Syntax)#center_align-2

The function syntax was changed for easier use. This was added if the a coder ever wanted to save the value for a specific string and then use it later.

😉

**Comment by MFReaper** [comment]
Please check the following link:
https://github.com/MFReaper/HeaderFile-Lexicon/wiki/Functions-(Syntax)#center_align-2

The function syntax was changed for easier use. This was added if the a coder ever wanted to save the value for a specific string and then use it later.

😉

**Comment by nerd-deus** [comment]
oh right, i was not using the function properly then, but yeah the `center_aligh( char* )` does take the `put pointer` to the top of the console i.e. the first line when console starts.

**Comment by MFReaper** [comment]
Ahh...Sorry

That was a stupid bug. Gave `0` to as a parameter to `Y` in `gotoXY( X, Y, R )` instead of `GetY()`
